services:
  ladybug-docs-server:
    image: ghcr.io/ladybugdb/dev-docs
    pull_policy: always
    ports:
      - "8082:80"
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
